"""
    Loads and plots the data generated by Simulation.py using matplotlib.
"""

from NumSim.SimData import SData
import matplotlib.pyplot as plt


def plot_exp_decay(data):
    tv = data.tv
    xv = data.xv

    fig, ax = plt.subplots(1, 1, figsize=(10, 6))

    ax.plot(tv, xv, color="C0")

    ax.set_xlabel("Time $t$")
    ax.set_ylabel("$x(t)$")

    plt.tight_layout()
    plt.show()


if (__name__ == "__main__"):
    SData.base_path = "Data/"
    data = SData("exp_decay_example.dill")
    plot_exp_decay(data)
