"""
    Loads and plots the data generated by Simulation.py using matplotlib.
"""

import matplotlib.pyplot as plt
from QIFSystems import QIFData


def plot_potential(data: QIFData):
    tv = data.tv
    xv = data.xv

    fig, ax = plt.subplots(1, 1, figsize=(10, 6))

    ax.plot(tv, xv[:, 0], label="QIF neuron 1")
    ax.plot(tv, xv[:, 1], label="QIF neuron 2")

    ax.set_xlabel("Time $t$")
    ax.set_ylabel("$V(t)$")

    ax.legend()

    plt.tight_layout()


if (__name__ == "__main__"):
    data = QIFData("Data/QIF2Example.dill")

    plot_potential(data)
    plt.savefig("Results/QIF2Example.pdf")
    plt.show()
