"""
    Loads and plots the data generated by Simulation.py using matplotlib.
"""

import matplotlib.pyplot as plt
from QIFSystems import QIFData
from QIFSystems.NeuralMass import NMData

import numpy as np


def get_spike_scatter(data, idx=None):
    taui = data.taui
    if (idx is None):
        idx = range(data.p.N)

    xs = []
    ys = []
    for i, ni in enumerate(idx):
        tk = np.array(taui[ni])
        xs.extend(tk)
        ys.extend([i] * len(tk))

    return np.array(xs), np.array(ys)


def plot_dynamics(data_net: QIFData, data_NM: NMData):
    p = data_NM.p

    Iextv = np.array([p.Iext(t) for t in data_NM.tv])
    spike_tv, spike_idx = get_spike_scatter(data_net, np.random.choice(p.N, p.N, replace=False))

    spike_tv *= p.taum
    data_net.atv *= p.taum
    data_net.avgrv /= p.taum

    data_NM.tv *= p.taum
    data_NM.xv[:, 0] /= p.taum

    net_kwargs = dict(lw=1, alpha=0.7, color="black")
    NM_kwargs = dict(lw=1, alpha=1, color="red")

    fig, ax = plt.subplots(6, 1, figsize=(10, 8), sharex=True,
                           gridspec_kw=dict(height_ratios=[0.5, 1, 1, 1, 1, 1]))

    ax[0].margins(y=0.2)
    ax[0].plot(data_NM.tv, Iextv, color="black")

    ax[1].scatter(spike_tv, spike_idx, marker=".", color=net_kwargs["color"], alpha=0.5,
                  edgecolors="none", s=2)
    ax[1].set_ylim(0, p.N)
    ax[2].plot(data_net.atv, data_net.avgrv, **net_kwargs)
    ax[3].plot(data_net.atv, data_net.avgvv, **net_kwargs)
    net_kwargs.update(lw=5, alpha=0.4)
    ax[4].plot(data_net.atv, data_net.avgdv, **net_kwargs)
    ax[5].plot(data_net.atv, data_net.avguv, **net_kwargs)

    for k in range(4):
        ax[k + 2].plot(data_NM.tv, data_NM.xv[:, k], **NM_kwargs)

    ax[0].set_xlim(0, data_NM.tv[-1])
    ax[0].set_ylabel("$I(t)$")
    ax[1].set_ylabel("Neuron $i$")
    ax[2].set_ylabel("$r(t)$ [Hz]")
    ax[3].set_ylabel("$v(t)$")
    ax[4].set_ylabel("$x(t)$")
    ax[5].set_ylabel("$u(t)$")
    ax[-1].set_xlabel("Time $t$ [s]")

    # ax.legend()
    fig.align_labels()
    plt.tight_layout()


if (__name__ == "__main__"):
    save_name = "MesoscopicSTP"

    data_net = QIFData(f"Data/{save_name}_network.dill")
    data_NM = NMData(f"Data/{save_name}_NM.dill")
    plot_dynamics(data_net, data_NM)
    plt.savefig("Results/NetworkQIFExample.png", dpi=300)
    plt.show()
